### ISSUE TITLE
Are there any samples for this theme?

### ISSUE THREAD

**Issue by chrislconover** [SotiriosVrachas/jekyll-theme-startbootstrap-agency#2]
Hi,

Are there any samples for this theme?   I have been - to the best of my knowledge, following along, but have run issues, trying to figure out missing properties and and the like.  For example, the timeline images don't render properly for me, I get clipped, and distorted circles that don't like up with the modal views.  

Is there a working sample that could act as a guide?

Thanks!

**Comment by SotiriosVrachas** [comment]
This? https://github.com/SotiriosVrachas/jekyll-theme-startbootstrap-agency-child

I haven't used the timeliness in any other project.
