### ISSUE TITLE
Centering of team and clients

### ISSUE THREAD

**Issue by Blunde1** [SotiriosVrachas/jekyll-theme-startbootstrap-agency#3]
Hi,

Thank you for this amazing theme!

If the number of team members and clients are less than 3 and 4 respectively, it will still be left aligned. Is there any way to center this?

Thank you!

**Comment by SotiriosVrachas** [comment]
Hello,

You can use ` justify-content-center` like so:

```
<div class="row justify-content-center">
          <div class="col-sm-4">
            <div class="team-member">
              <img class="mx-auto rounded-circle" src="img/team/1.jpg" alt="">
```
